### PR TITLE
Update to the tip of `juce:develop`

### PR DESCRIPTION
**Pull request by jamierpond**
So I think this is pretty much good to go. Please have a check and spot if there is any weirdness in the merge. The app seems to behave how I expect it to using this branch now :)

I'm thinking we should be updating Tracktion+JUCE every 4 weeks, with a staged rollout on the App Store when that happens in case we need to stop the roll out for any reason (e.g. the tracktion/juce update causes crashes).

### CODE REVIEW

**Comment by jklein24** [comment]
This seems cool to me, but wondering about the test strategy here. If we merge this, we have to merge the other branch to develop too and there's no turning back for daily releases haha. If we wanted to do one-off test builds instead, we could have your mayk repo branch just point at this `better-juce-update` branch and we could push test builds from there? Either way is cool, just want to clarify what the plan is on that. I guess just depends how confident you're feeling in the change ;-)

**Comment by jamierpond** [comment]
@jklein24 I don't think it would be an awful thing to go for a one-off test build to begin with to be fair! Maybe over the weekend the app center builds can come from this branch, and jam it out from there?

**Comment by jamierpond** [comment]
The only thing I'm just digging now is the Robot filter doesn't seem to be working for some reason.

**Review by jklein24 — APPROVED** [review]
kk Let's go for it then :-)

**Pull request merged**
